# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-07 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_wife'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(default='xx@hx.cn', max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
